                        1. Numpy 
                        2. Pandas
                        3. matplot
                        4. seaborn
                        5. opencv
                        6. scipy
                        7. sklearn
                        

In [1]:
a=[10,20,30,40,50]
b=[1,2,3,4,5,]

In [2]:
a*b

TypeError: can't multiply sequence by non-int of type 'list'

In [3]:
a+b

[10, 20, 30, 40, 50, 1, 2, 3, 4, 5]

# Arrays-----

In [4]:
# 1D----array 
# 2D
# 3D

In [5]:
# list to array with array function
# arange 

In [6]:
a

[10, 20, 30, 40, 50]

In [7]:
# pip install numpy
import numpy as np

In [8]:
r=np.array(a)

In [9]:
r

array([10, 20, 30, 40, 50])

In [10]:
r.dtype

dtype('int32')

In [11]:
type(r)

numpy.ndarray

In [12]:
type(a)

list

In [14]:
r.ndim

1

In [15]:
r

array([10, 20, 30, 40, 50])

In [20]:
r1=np.arange(10,20,2)

In [21]:
r1

array([10, 12, 14, 16, 18])

In [22]:
r1.shape

(5,)

In [23]:
w=np.arange(20)

In [24]:
w

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [25]:
q=w.reshape(4,5) # row,col   

In [26]:
q

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [27]:
x=[1,2,3]
y=[4,5,6]
z=[7,8,9]

In [28]:
t=np.array([x,y,z])

In [29]:
t

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])